using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Net;
using System.Net.Mail;
using System.Security.Cryptography; 
using System.Text;
using Equipment_hub.Data.Models;

namespace Equipment_hub.BusinessLogic
{ 
        public enum eventzz 
        { 
        SUCCESSFUL_ACTIVITY_STATUS_ADD = 1,
FAILED_ACTIVITY_STATUS_ADD = 2,
ERROR_ACTIVITY_STATUS_ADD = 3,
SUCCESSFUL_ACTIVITY_STATUS_GET = 4,
FAILED_ACTIVITY_STATUS_GET = 5,
ERROR_ACTIVITY_STATUS_GET = 6,
SUCCESSFUL_ACTIVITY_STATUS_UPDATE = 7,
FAILED_ACTIVITY_STATUS_UPDATE = 8,
ERROR_ACTIVITY_STATUS_UPDATE = 9,
SUCCESSFUL_AUTHENTICATE_ADMIN_ADD = 10,
FAILED_AUTHENTICATE_ADMIN_ADD = 11,
ERROR_AUTHENTICATE_ADMIN_ADD = 12,
SUCCESSFUL_AUTHENTICATE_ADMIN_GET = 13,
FAILED_AUTHENTICATE_ADMIN_GET = 14,
ERROR_AUTHENTICATE_ADMIN_GET = 15,
SUCCESSFUL_AUTHENTICATE_ADMIN_UPDATE = 16,
FAILED_AUTHENTICATE_ADMIN_UPDATE = 17,
ERROR_AUTHENTICATE_ADMIN_UPDATE = 18,
SUCCESSFUL_AUTHENTICATE_CUSTOMER_ADD = 19,
FAILED_AUTHENTICATE_CUSTOMER_ADD = 20,
ERROR_AUTHENTICATE_CUSTOMER_ADD = 21,
SUCCESSFUL_AUTHENTICATE_CUSTOMER_GET = 22,
FAILED_AUTHENTICATE_CUSTOMER_GET = 23,
ERROR_AUTHENTICATE_CUSTOMER_GET = 24,
SUCCESSFUL_AUTHENTICATE_CUSTOMER_UPDATE = 25,
FAILED_AUTHENTICATE_CUSTOMER_UPDATE = 26,
ERROR_AUTHENTICATE_CUSTOMER_UPDATE = 27,
SUCCESSFUL_AUTHENTICATE_VENDOR_ADD = 28,
FAILED_AUTHENTICATE_VENDOR_ADD = 29,
ERROR_AUTHENTICATE_VENDOR_ADD = 30,
SUCCESSFUL_AUTHENTICATE_VENDOR_GET = 31,
FAILED_AUTHENTICATE_VENDOR_GET = 32,
ERROR_AUTHENTICATE_VENDOR_GET = 33,
SUCCESSFUL_AUTHENTICATE_VENDOR_UPDATE = 34,
FAILED_AUTHENTICATE_VENDOR_UPDATE = 35,
ERROR_AUTHENTICATE_VENDOR_UPDATE = 36,
SUCCESSFUL_CUSTOMER_COMPANY_ADD = 37,
FAILED_CUSTOMER_COMPANY_ADD = 38,
ERROR_CUSTOMER_COMPANY_ADD = 39,
SUCCESSFUL_CUSTOMER_COMPANY_GET = 40,
FAILED_CUSTOMER_COMPANY_GET = 41,
ERROR_CUSTOMER_COMPANY_GET = 42,
SUCCESSFUL_CUSTOMER_COMPANY_UPDATE = 43,
FAILED_CUSTOMER_COMPANY_UPDATE = 44,
ERROR_CUSTOMER_COMPANY_UPDATE = 45,
SUCCESSFUL_DURATION_TYPE_ADD = 46,
FAILED_DURATION_TYPE_ADD = 47,
ERROR_DURATION_TYPE_ADD = 48,
SUCCESSFUL_DURATION_TYPE_GET = 49,
FAILED_DURATION_TYPE_GET = 50,
ERROR_DURATION_TYPE_GET = 51,
SUCCESSFUL_DURATION_TYPE_UPDATE = 52,
FAILED_DURATION_TYPE_UPDATE = 53,
ERROR_DURATION_TYPE_UPDATE = 54,
SUCCESSFUL_EQUIPMENT_ADD = 55,
FAILED_EQUIPMENT_ADD = 56,
ERROR_EQUIPMENT_ADD = 57,
SUCCESSFUL_EQUIPMENT_GET = 58,
FAILED_EQUIPMENT_GET = 59,
ERROR_EQUIPMENT_GET = 60,
SUCCESSFUL_EQUIPMENT_UPDATE = 61,
FAILED_EQUIPMENT_UPDATE = 62,
ERROR_EQUIPMENT_UPDATE = 63,
SUCCESSFUL_EQUIPMENT_ACTIVITY_ADD = 64,
FAILED_EQUIPMENT_ACTIVITY_ADD = 65,
ERROR_EQUIPMENT_ACTIVITY_ADD = 66,
SUCCESSFUL_EQUIPMENT_ACTIVITY_GET = 67,
FAILED_EQUIPMENT_ACTIVITY_GET = 68,
ERROR_EQUIPMENT_ACTIVITY_GET = 69,
SUCCESSFUL_EQUIPMENT_ACTIVITY_UPDATE = 70,
FAILED_EQUIPMENT_ACTIVITY_UPDATE = 71,
ERROR_EQUIPMENT_ACTIVITY_UPDATE = 72,
SUCCESSFUL_EQUIPMENT_TYPE_ADD = 73,
FAILED_EQUIPMENT_TYPE_ADD = 74,
ERROR_EQUIPMENT_TYPE_ADD = 75,
SUCCESSFUL_EQUIPMENT_TYPE_GET = 76,
FAILED_EQUIPMENT_TYPE_GET = 77,
ERROR_EQUIPMENT_TYPE_GET = 78,
SUCCESSFUL_EQUIPMENT_TYPE_UPDATE = 79,
FAILED_EQUIPMENT_TYPE_UPDATE = 80,
ERROR_EQUIPMENT_TYPE_UPDATE = 81,
SUCCESSFUL_RENT_RATE_ADD = 82,
FAILED_RENT_RATE_ADD = 83,
ERROR_RENT_RATE_ADD = 84,
SUCCESSFUL_RENT_RATE_GET = 85,
FAILED_RENT_RATE_GET = 86,
ERROR_RENT_RATE_GET = 87,
SUCCESSFUL_RENT_RATE_UPDATE = 88,
FAILED_RENT_RATE_UPDATE = 89,
ERROR_RENT_RATE_UPDATE = 90,
SUCCESSFUL_RIGHT_ADMIN_ADD = 91,
FAILED_RIGHT_ADMIN_ADD = 92,
ERROR_RIGHT_ADMIN_ADD = 93,
SUCCESSFUL_RIGHT_ADMIN_GET = 94,
FAILED_RIGHT_ADMIN_GET = 95,
ERROR_RIGHT_ADMIN_GET = 96,
SUCCESSFUL_RIGHT_ADMIN_UPDATE = 97,
FAILED_RIGHT_ADMIN_UPDATE = 98,
ERROR_RIGHT_ADMIN_UPDATE = 99,
SUCCESSFUL_RIGHT_VENDOR_ADD = 100,
FAILED_RIGHT_VENDOR_ADD = 101,
ERROR_RIGHT_VENDOR_ADD = 102,
SUCCESSFUL_RIGHT_VENDOR_GET = 103,
FAILED_RIGHT_VENDOR_GET = 104,
ERROR_RIGHT_VENDOR_GET = 105,
SUCCESSFUL_RIGHT_VENDOR_UPDATE = 106,
FAILED_RIGHT_VENDOR_UPDATE = 107,
ERROR_RIGHT_VENDOR_UPDATE = 108,
SUCCESSFUL_ROLE_ADMIN_ADD = 109,
FAILED_ROLE_ADMIN_ADD = 110,
ERROR_ROLE_ADMIN_ADD = 111,
SUCCESSFUL_ROLE_ADMIN_GET = 112,
FAILED_ROLE_ADMIN_GET = 113,
ERROR_ROLE_ADMIN_GET = 114,
SUCCESSFUL_ROLE_ADMIN_UPDATE = 115,
FAILED_ROLE_ADMIN_UPDATE = 116,
ERROR_ROLE_ADMIN_UPDATE = 117,
SUCCESSFUL_ROLE_RIGHT_ADMIN_ADD = 118,
FAILED_ROLE_RIGHT_ADMIN_ADD = 119,
ERROR_ROLE_RIGHT_ADMIN_ADD = 120,
SUCCESSFUL_ROLE_RIGHT_ADMIN_GET = 121,
FAILED_ROLE_RIGHT_ADMIN_GET = 122,
ERROR_ROLE_RIGHT_ADMIN_GET = 123,
SUCCESSFUL_ROLE_RIGHT_ADMIN_UPDATE = 124,
FAILED_ROLE_RIGHT_ADMIN_UPDATE = 125,
ERROR_ROLE_RIGHT_ADMIN_UPDATE = 126,
SUCCESSFUL_ROLE_RIGHT_VENDOR_ADD = 127,
FAILED_ROLE_RIGHT_VENDOR_ADD = 128,
ERROR_ROLE_RIGHT_VENDOR_ADD = 129,
SUCCESSFUL_ROLE_RIGHT_VENDOR_GET = 130,
FAILED_ROLE_RIGHT_VENDOR_GET = 131,
ERROR_ROLE_RIGHT_VENDOR_GET = 132,
SUCCESSFUL_ROLE_RIGHT_VENDOR_UPDATE = 133,
FAILED_ROLE_RIGHT_VENDOR_UPDATE = 134,
ERROR_ROLE_RIGHT_VENDOR_UPDATE = 135,
SUCCESSFUL_ROLE_VENDOR_ADD = 136,
FAILED_ROLE_VENDOR_ADD = 137,
ERROR_ROLE_VENDOR_ADD = 138,
SUCCESSFUL_ROLE_VENDOR_GET = 139,
FAILED_ROLE_VENDOR_GET = 140,
ERROR_ROLE_VENDOR_GET = 141,
SUCCESSFUL_ROLE_VENDOR_UPDATE = 142,
FAILED_ROLE_VENDOR_UPDATE = 143,
ERROR_ROLE_VENDOR_UPDATE = 144,
SUCCESSFUL_SELECTED_EQUIPEMENT_ADD = 145,
FAILED_SELECTED_EQUIPEMENT_ADD = 146,
ERROR_SELECTED_EQUIPEMENT_ADD = 147,
SUCCESSFUL_SELECTED_EQUIPEMENT_GET = 148,
FAILED_SELECTED_EQUIPEMENT_GET = 149,
ERROR_SELECTED_EQUIPEMENT_GET = 150,
SUCCESSFUL_SELECTED_EQUIPEMENT_UPDATE = 151,
FAILED_SELECTED_EQUIPEMENT_UPDATE = 152,
ERROR_SELECTED_EQUIPEMENT_UPDATE = 153,
SUCCESSFUL_VENDOR_COMPANY_ADD = 154,
FAILED_VENDOR_COMPANY_ADD = 155,
ERROR_VENDOR_COMPANY_ADD = 156,
SUCCESSFUL_VENDOR_COMPANY_GET = 157,
FAILED_VENDOR_COMPANY_GET = 158,
ERROR_VENDOR_COMPANY_GET = 159,
SUCCESSFUL_VENDOR_COMPANY_UPDATE = 160,
FAILED_VENDOR_COMPANY_UPDATE = 161,
ERROR_VENDOR_COMPANY_UPDATE = 162,
SUCCESSFUL_VENDOR_PAYMENTS_ADD = 163,
FAILED_VENDOR_PAYMENTS_ADD = 164,
ERROR_VENDOR_PAYMENTS_ADD = 165,
SUCCESSFUL_VENDOR_PAYMENTS_GET = 166,
FAILED_VENDOR_PAYMENTS_GET = 167,
ERROR_VENDOR_PAYMENTS_GET = 168,
SUCCESSFUL_VENDOR_PAYMENTS_UPDATE = 169,
FAILED_VENDOR_PAYMENTS_UPDATE = 170,
ERROR_VENDOR_PAYMENTS_UPDATE = 171 
        } 
    public class Audit 
    {  
        public static void InsertAudit(EventLog newEvent, string callerFormName)
        {
            var context = Equipment_hub.Data.Models.Equipment_hub.GetInstance();
            try
            {
                context.Insert<EventLog>(newEvent);
            }
            catch (Exception ex)
            {
            
            }
        }
        public static void InsertAudit(int eventId, string eventDetails, long userId, bool userevent)
        { 
            EventLog audit = new EventLog();
            audit.Description =  eventDetails;
            audit.Eventid = eventId;
            audit.Userid = userId;
            audit.Userevent = userevent;
            audit.Eventdate = DateTime.Now;
            InsertAudit(audit, "");
        }
        public static string GetEncodedHash(string password, string salt)
        {
           MD5 md5 = new MD5CryptoServiceProvider();
           byte [] digest = md5.ComputeHash(Encoding.UTF8.GetBytes(password + salt));
           string base64digest = Convert.ToBase64String(digest, 0, digest.Length);
           return base64digest.Substring(0, base64digest.Length-2);
        }

    public static  void protocol()

    {

        ServicePointManager.SecurityProtocol |= (SecurityProtocolType)48 | (SecurityProtocolType)192 | (SecurityProtocolType)768 | (SecurityProtocolType)3072;

    }

        public static string SendMail(string email, string mailSubject, string mailBody, string callerFormName)
        {
            bool iSBodyHtml = false;
            string result = "";
            try
            {
                  MailMessage mail = new MailMessage();
                  mail.From = new MailAddress(ConfigurationManager.AppSettings["email"]);
                  mail.To.Add(email);
                  mail.Subject = mailSubject;
                  mail.IsBodyHtml = true;
                  mail.Body = mailBody;
                  SmtpClient smtp = new SmtpClient(ConfigurationManager.AppSettings["client"]);
                  smtp.Port = int.Parse(ConfigurationManager.AppSettings["port"]);
                  smtp.Credentials = new NetworkCredential(ConfigurationManager.AppSettings["username_email"], ConfigurationManager.AppSettings["password"]); 
                  smtp.Send(mail); 
            }
            catch (Exception ex)
            { 
                result = ex.Message;
            }
            finally
            { 
            }
            return result;
        }

        public static string GenerateRandom()
        {
            string result = "";
            string chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
            var stringChars = new char[5];
            var random = new Random();

            for (int i = 0; i < stringChars.Length; i++)
            {
                stringChars[i] = chars[random.Next(chars.Length)];
            }

            result = new String(stringChars);
            return result;
        }    }
}
